version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "${DB_PORT}:5432"
  django_api:
    build:
      context: .
      dockerfile: docker_files/Dockerfile_django_api
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/back-end
    depends_on:
      - postgres
  react:
    build:
      context: .
      dockerfile: docker_files/Dockerfile_react_fe
    ports:
      - "80:80"
    volumes:
      - ./front-end/dist:/usr/share/nginx/html
      - ./docker_files/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django_api
      