# Use an official Python runtime as a parent image
FROM python:latest

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /back-end

# Copy the dependencies file to the working directory
COPY ../back-end/requirements.txt /back-end/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /code/
COPY ../back-end/ /back-end/

RUN echo "DB_NAME=${DB_NAME}" >> .env \
    && echo "DB_USER=${DB_USER}" >> .env \
    && echo "DB_PASSWORD=${DB_PASSWORD}" >> .env \
    && echo "DJ_DB_HOST=${DJ_DB_HOST}" >> .env \
    && echo "DJ_DB_PORT=${DJ_DB_PORT}" >> .env \
    && echo "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}" >> .env

RUN python3 manage.py makemigrations

RUN python3 manage.py migrate

# Expose port 8000 to the outside world
EXPOSE 8000

# Run Gunicorn server when the container launches
CMD ["python3","manage.py","test","tests.test_user_test_models"]
