# Use an official Python runtime as a parent image
FROM python:latest

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /back-end

# Copy the dependencies file to the working directory
COPY ../back-end/requirements.txt /back-end/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /code/
COPY ../back-end/ /back-end/

# Expose port 8000 to the outside world
EXPOSE 8000

# Run Gunicorn server when the container launches
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "fitness_proj.wsgi:application"]
