# Use the official PostgreSQL base image
FROM postgres:latest

# Enable SUPERUSER rights for the database
ENV POSTGRES_INITDB_ARGS="--encoding=UTF-8 --lc-collate=C --lc-ctype=C --data-checksums"
# Expose port 5432 for PostgreSQL
EXPOSE 5432
# Start the PostgreSQL server
CMD ["postgres"]