# Use the official PostgreSQL base image
FROM postgres:latest

# Set environment variables for the PostgreSQL database
# ENV POSTGRES_DB=$DB_NAME
# ENV POSTGRES_USER=$DB_USER
# ENV POSTGRES_PASSWORD=$DB_PASSWORD

# Expose port 5432 for PostgreSQL

# Enable SUPERUSER rights for the database
ENV POSTGRES_INITDB_ARGS="--encoding=UTF-8 --lc-collate=C --lc-ctype=C --data-checksums"

EXPOSE 5432
# Start the PostgreSQL server
CMD ["postgres"]