# Generated by Django 5.0.3 on 2024-04-15 18:52

import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='password',
            field=models.CharField(max_length=255, validators=[user_app.validators.validate_password]),
        ),
    ]
