# Generated by Django 5.0.3 on 2024-04-15 17:20

import django.core.validators
import django.db.models.deletion
import user_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[user_app.validators.weight_validator])),
                ('bio', models.TextField(validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxValueValidator(500)])),
                ('picture', models.ImageField(blank=True, default='settings.DEFAULT_PICTURE_PATH', null=True, upload_to='user_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
