name: Running Django Unit Tests

on:
  push:
    branches: ["main", "actions", "models"]
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql -y
          sudo apt-get install postgresql-contrib -y
          sudo apt-get install postgresql-client -y
          echo waiting...
          sleep 6
          sudo service postgresql start
          sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"CREATE USER runner WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '';\""
          sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"CREATE USER ${{secrets.DB_USER}} WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '${{secrets.DB_PASSWORD}}';\""
          sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"create database ${{secrets.DB_NAME}};\""
          echo finished pg commands...
          sudo service postgresql restart

      - name: Build env file
        working-directory: back-end
        run: |
          env > .env
          ls -a
          cat .env
          
      - name: Testing Django Connection
        run: |
          sudo su - postgres -c "psql --echo-all -h ${{secrets.DJ_DB_HOST}} -p ${{secrets.DJ_DB_PORT}} -U ${{secrets.DB_USER}} "
          ${{secrets.DB_PASSWORD}}

      - name: Install Dependencies
        working-directory: back-end
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Makemigrations && migrate
        working-directory: back-end
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate

      - name: Run Unit Tests
        working-directory: back-end
        run: python3 manage.py test tests.test_user.test_models
