name: Running Django Unit Tests

on:
  push:
    branches: ["main", "actions", "models"]
  workflow_dispatch:

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Python
          uses: actions/setup-python@v5
        
        - name: Install Dependencies
          working-directory: back-end
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
        
        - name: Run Unit Tests
          working-directory: back-end
          run: python3 manage.py test tests.test_user
          
