name: Checking env secrets presence

on:
    push:
        branches:
            - main
            - actions

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checout@v2

            - name: Use a secret
              run: echo "My db user name ${{ secrets.DB_USER }}"
