name: Checking env secrets presence within repo

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use a secret
              run: echo "My db user name ${{ secrets.DB_USER }}"
